package de.tum.ar.ai.ksdaccess.neo4j;

public enum BuildingType {
    BLOCKRANDBEBAUUNG,
    BAULUECKE,
    ECKHAEUSER,
    BRANDWAND,
    SOLITAER,
    FREISTEHENDEZEILE,
    WOHNTUERME,
    TERASSENHAEUSER,
    RAUMBILDENDESTRUKTUREN,
    EINZELHAEUSER,
    DOPPELHAEUSER,
    REIHENHAEUSER,
    WOHNANLAGE;
}
